name: attend_me
description: Presence app with GetX and Hive
publish_to: "none"
version: 1.0.0+1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/attendme.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/attendme.png"
    background_color: "#F9F9F9"
    theme_color: "#000000"

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get:
  hive:
  hive_flutter:
  path_provider:
  intl:
  percent_indicator: ^4.2.2
  http:
  url_launcher:
  google_sign_in: ^6.0.0
  uuid: ^4.4.2
  csv: ^6.0.0
  shared_preferences: ^2.5.3
  googleapis: any
  googleapis_auth: any
  excel: ^2.0.0
  file_picker: ^8.0.0
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  build_runner:
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/attendme.png
